-- string_instrumentテーブル
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (1, 'アコースティックギター', 'str01.jpg', '生音が響くため屋外やスタジオ等がおすすめ。エレキギターとは違い弦が硬いため、抑えるのには良い練習になります。', 500, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (2, 'アコースティックギター', 'str02.jpg', '生音が響くため屋外やスタジオ等がおすすめ。エレキギターとは違い弦が硬いため、抑えるのには良い練習になります。', 500, 6, '左');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (3, 'エレキギターレスポール', 'str03.jpg', '太く甘いサスティン長めが特徴。ロックなで重低音の曲を演奏におすすめ。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 700, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (4, 'エレキギターレスポール', 'str04.jpg', '太く甘いサスティン長めが特徴。ロックなで重低音の曲を演奏におすすめ。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 700, 6, '左');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (5, 'エレキギターストラトキャスター6弦', 'str05.jpg', 'クリアな音からレスポールのような重低音に近いまでの多彩な表現を可としています。演奏するジャンルが特に決まっていなければ、どのジャンルにも対応できるので初心者におすすめです。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 700, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (6, 'エレキギターストラトキャスター6弦', 'str06.jpg', 'クリアな音からレスポールのような重低音に近いまでの多彩な表現を可としています。演奏するジャンルが特に決まっていなければ、どのジャンルにも対応できるので初心者におすすめです。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 900, 6, '左');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (7, 'エレキギタージャズマスター6弦', 'str07.jpg', '太く甘い中低域豊かなトーンが生まれ、クリーン時は繊細で温かみがあり、歪ませるとジャキジャキとした高域の抜けが良いザクザクサウンドになります。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 900, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (8, 'エレキギタージャガー6弦', 'str08.jpg', 'シャープでブライトな高域強調のエッジーなトーンが特徴で、クリーン時はツゥワングとチムのような歯切れ良さ、歪み時はパンチーで直接的な響きが魅力です。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 900, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (9, 'エレキギターテレキャスター', 'str09.jpg', '鋭くパンチの効いたクリアでジャカジャカなサウンドが特徴です。一音一音が目立つため、目立つような演奏をするのにおすすめです。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 700, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (10, 'エレキギターテレキャスター', 'str10.jpg', '鋭くパンチの効いたクリアでジャカジャカなサウンドが特徴です。一音一音が目立つため、目立つような演奏をするのにおすすめです。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 700, 6, '左');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (11, 'エレクトリックアコースティックギター', 'str11.jpg', 'アコースティックギターにアンプ接続ができるようになり、いろんな音が楽しめます。紹介したとおり、アコースティックギターにもなるため、生音が響くため場所に注意してください。アンプの貸し出しもしています。', 700, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (12, 'エレクトリックアコースティックギター', 'str12.jpg', 'アコースティックギターにアンプ接続ができるようになり、いろんな音が楽しめます。紹介したとおり、アコースティックギターにもなるため、生音が響くため場所に注意してください。アンプの貸し出しもしています。', 700, 6, '左');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (13, 'セミアコースティックギター', 'str13.jpg', 'セミアコは「センターブロック」と呼ばれる木材が中に入っており、ハウリングに強くロックやブルースなど万能に対応します。サウンドホールがあるので多少は響くので練習場所には注意してください。アンプ貸出もしています。', 800, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (14, 'セミアコースティックギター', 'str14.jpg', 'セミアコは「センターブロック」と呼ばれる木材が中に入っており、ハウリングに強くロックやブルースなど万能に対応します。サウンドホールがあるので多少は響くので練習場所には注意してください。アンプ貸出もしています。', 800, 6, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (15, 'フルアコースティックギター', 'str15.jpg', 'フルアコは内部が完全に空洞で、温かみのある箱鳴り感が特徴、主にジャズで使用されます。 サウンドホールがあるので多少は響くので練習場所には注意してください。アンプ貸出もしています。', 800, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (16, 'フルアコースティックギター', 'str16.jpg', 'フルアコは内部が完全に空洞で、温かみのある箱鳴り感が特徴、主にジャズで使用されます。 サウンドホールがあるので多少は響くので練習場所には注意してください。アンプ貸出もしています。', 800, 6, '左');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (17, 'アコースティックベース4弦', 'str17.jpg', 'アコースティックギターのベースバージョンとなります。生音が響くため屋外やスタジオ等がおすすめ。エレキベースとは違い弦が硬いため、抑えるのには良い練習になります。', 500, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (18, 'アコースティックベース4弦', 'str18.jpg', 'アコースティックギターのベースバージョンとなります。生音が響くため屋外やスタジオ等がおすすめ。エレキベースとは違い弦が硬いため、抑えるのには良い練習になります。', 500, 6, '左');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (19, 'エレキベースジャズベース4弦', 'str21.jpg', 'シャープな音からプレベに近い低音を表現できます。また、どのジャンルにも対応できるので初心者におすすめです。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 700, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (20, 'エレキベースジャズベース4弦', 'str22.jpg', 'シャープな音からプレベに近い低音を表現できます。また、どのジャンルにも対応できるので初心者におすすめです。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 700, 6, '左');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (21, 'エレキベースジャズベース5弦', 'str23.jpg', 'シャープな音からプレベに近い低音を表現できます。また、どのジャンルにも対応できるので初心者におすすめです。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。さらに低い弦を追加することで、ドロップチューニングも必要なくなるので、さらに多くのジャンルの曲の演奏が可能となります。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 900, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (22, 'エレキベースジャズベース5弦', 'str24.jpg', 'シャープな音からプレベに近い低音を表現できます。また、どのジャンルにも対応できるので初心者におすすめです。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。さらに低い弦を追加することで、ドロップチューニングも必要なくなるので、さらに多くのジャンルの曲の演奏が可能となります。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 1000, 6, '左');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (23, 'エレキベースプレシジョンベース4弦', 'str25.jpg', '太く柔らかなサウンドやしっかりとした低音が出せるのが特徴。ロック、メタル、ポップスを演奏するのにおすすめ。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 800, 10, '右');
INSERT IGNORE INTO string_instrument (id, name, image_name, description, price, capacity, handedness ) VALUES (24, 'エレキベースプレシジョンベース4弦', 'str26.jpg', '太く柔らかなサウンドやしっかりとした低音が出せるのが特徴。ロック、メタル、ポップスを演奏するのにおすすめ。アンプも貸出可のため、ヘッドホンをつけて自宅で練習もできます。', 800, 6, '左');

-- rolesテーブル
INSERT IGNORE INTO roles (id, name) VALUES (1, 'ROLE_GENERAL');
INSERT IGNORE INTO roles (id, name) VALUES (2, 'ROLE_ADMIN');

-- usersテーブル
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (1, '侍 太郎', 'サムライ タロウ', '101-0022', '東京都千代田区神田練塀町300番地', '090-1234-5678', 'taro.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 1, true);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (2, '侍 花子', 'サムライ ハナコ', '101-0022', '東京都千代田区神田練塀町300番地', '090-1234-5678', 'hanako.samurai@example.com', '$2a$10$2JNjTwZBwo7fprL2X4sv.OEKqxnVtsVQvuXDkI8xVGix.U3W5B7CO', 2, true);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (3, '侍 義勝', 'サムライ ヨシカツ', '638-0644', '奈良県五條市西吉野町湯川X-XX-XX', '090-1234-5678', 'yoshikatsu.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (4, '侍 幸美', 'サムライ サチミ', '342-0006', '埼玉県吉川市南広島X-XX-XX', '090-1234-5678', 'sachimi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (5, '侍 雅', 'サムライ ミヤビ', '527-0209', '滋賀県東近江市佐目町X-XX-XX', '090-1234-5678', 'miyabi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (6, '侍 正保', 'サムライ マサヤス', '989-1203', '宮城県柴田郡大河原町旭町X-XX-XX', '090-1234-5678', 'masayasu.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (7, '侍 真由美', 'サムライ マユミ', '951-8015', '新潟県新潟市松岡町X-XX-XX', '090-1234-5678', 'mayumi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (8, '侍 安民', 'サムライ ヤスタミ', '241-0033', '神奈川県横浜市旭区今川町X-XX-XX', '090-1234-5678', 'yasutami.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (9, '侍 章緒', 'サムライ アキオ', '739-2103', '広島県東広島市高屋町宮領X-XX-XX', '090-1234-5678', 'akio.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (10, '侍 祐子', 'サムライ ユウコ', '601-0761', '京都府南丹市美山町高野X-XX-XX', '090-1234-5678', 'yuko.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (11, '侍 秋美', 'サムライ アキミ', '606-8235', '京都府京都市左京区田中西春菜町X-XX-XX', '090-1234-5678', 'akimi.samurai@example.com', 'password', 1, false);
INSERT IGNORE INTO users (id, name, furigana, postal_code, address, phone_number, email, password, role_id, enabled) VALUES (12, '侍 信平', 'サムライ シンペイ', '673-1324', '兵庫県加東市新定X-XX-XX', '090-1234-5678', 'shinpei.samurai@example.com', 'password', 1, false);

-- reservationsテーブル
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (1, 1, 1, '2023-04-01 8:00:00', '2023-04-01 10:00:00', 2, 1000);
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (2, 2, 1, '2023-04-01 8:00:00', '2023-04-01 11:00:00', 3, 1500);
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (3, 3, 1, '2023-04-01 8:00:00', '2023-04-01 12:00:00', 4, 2000);
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (4, 4, 1, '2023-04-01 8:00:00', '2023-04-01 13:00:00', 5, 2500);
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (5, 5, 1, '2023-04-01 8:00:00', '2023-04-01 14:00:00', 6, 3000);
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (6, 6, 1, '2023-04-01 8:00:00', '2023-04-01 10:00:00', 2, 1000);
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (7, 7, 1, '2023-04-01 8:00:00', '2023-04-01 11:00:00', 3, 1500);
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (8, 8, 1, '2023-04-01 8:00:00', '2023-04-01 12:00:00', 4, 2000);
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (9, 9, 1, '2023-04-01 8:00:00', '2023-04-01 13:00:00', 5, 2500);
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (10, 10, 1, '2023-04-01 8:00:00', '2023-04-01 14:00:00', 6, 3000);
INSERT IGNORE INTO reservations (id, string_instrument_id, user_id, rental_start_time, rental_end_time, rental_quantity, amount) VALUES (11, 11, 1, '2023-04-01 8:00:00', '2023-04-01 10:00:00', 2, 1000);